name             'netrc'
maintainer       'John Bellone'
maintainer_email 'jbellone@bloomberg.net'
license          'Apache 2.0'
description      'Installs/Configures netrc'
long_description 'Installs/Configures netrc'
version          '0.1.1'

depends 'chef-sugar'
depends 'chef-vault'
depends 'poise'
